#spring:
#  datasource:
#    username: root
#    password: Baba1973*
#    url: jdbc:mysql://localhost:3306/springbootjpadb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      dd-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect